name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/herokuu-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "turners-search-backend"
          heroku_email: "caedanlavender@gmail.com"
          healthcheck: "https://turners-search-backend.herokuapp.com/health"
          procfile: "web: npm start"